version: '3.8'

services:
  php74:
    build:
      context: .
      dockerfile: Dockerfile.74
    ports:
      - 80:80
    volumes:
      - ./php74:/var/www/html/

  php56:
    build:
      context: .
      dockerfile: Dockerfile.56
    ports:
      - 88:80
    volumes:
      - ./php56:/var/www/html/

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password #example of a password

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
